USE tienda;
SELECT * FROM producto;
SELECT nombre, precio FROM producto;
SHOW COLUMNS FROM producto;
SELECT nombre, precio AS '€', ROUND((precio * 1.12), 2) AS 'USD' FROM producto;
SELECT nombre AS 'nom de "producto"', precio AS 'euros', ROUND((precio * 1.12), 2) AS 'dòlars nord-americans' FROM producto;
SELECT UPPER(nombre), precio FROM producto;
SELECT LOWER(nombre), precio FROM producto;
SELECT nombre, UPPER(SUBSTRING(nombre, 1, 2)) FROM fabricante;
SELECT nombre, ROUND(precio) FROM producto;
SELECT precio, TRUNCATE(precio, 0) FROM producto;
SELECT codigo_fabricante FROM producto JOIN fabricante ON fabricante.codigo = producto.codigo_fabricante;
SELECT codigo_fabricante FROM producto JOIN fabricante ON fabricante.codigo = producto.codigo_fabricante GROUP BY codigo_fabricante;
SELECT nombre FROM fabricante ORDER BY nombre ASC;
SELECT nombre FROM fabricante ORDER BY nombre DESC;
SELECT nombre FROM producto ORDER BY nombre ASC, precio DESC;
SELECT * FROM fabricante LIMIT 5;
SELECT * FROM fabricante LIMIT 3,2;
SELECT nombre, precio FROM producto ORDER BY precio LIMIT 1;
SELECT nombre, precio FROM producto ORDER BY precio DESC LIMIT 1;
SELECT nombre FROM producto WHERE codigo_fabricante = 2;
SELECT producto.nombre, producto.precio, fabricante.nombre FROM producto JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo;
SELECT producto.nombre, producto.precio, fabricante.nombre FROM producto JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo ORDER BY fabricante.nombre;
SELECT producto.codigo, producto.nombre, producto.codigo_fabricante, fabricante.nombre FROM producto JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo;
SELECT producto.nombre, producto.precio, fabricante.nombre FROM producto JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo ORDER BY precio ASC LIMIT 1;
SELECT producto.nombre, producto.precio, fabricante.nombre FROM producto JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo ORDER BY precio DESC LIMIT 1;
SELECT producto.nombre FROM producto JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo WHERE fabricante.nombre = 'Lenovo';
SELECT producto.nombre FROM producto JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo WHERE fabricante.nombre = 'Crucial' AND producto.precio > 200;
SELECT producto.nombre FROM producto JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo WHERE fabricante.nombre REGEXP ('Asus|Hewlett-Packard|Seagate');
SELECT producto.nombre FROM producto JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo WHERE fabricante.nombre IN ('Asus', 'Hewlett-Packard', 'Seagate');
SELECT producto.nombre FROM producto JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo WHERE fabricante.nombre LIKE ('%e');
SELECT producto.nombre FROM producto JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo WHERE fabricante.nombre LIKE ('%w%');
SELECT producto.nombre, producto.precio, fabricante.nombre FROM producto JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo WHERE precio >= 180 ORDER BY producto.precio DESC, producto.nombre;
SELECT DISTINCT fabricante.codigo, fabricante.nombre FROM fabricante JOIN producto ON fabricante.codigo = producto.codigo_fabricante;
SELECT fabricante.nombre, GROUP_CONCAT(producto.nombre SEPARATOR ', ') AS productos FROM fabricante LEFT JOIN producto ON fabricante.codigo = producto.codigo_fabricante GROUP BY fabricante.nombre;
SELECT fabricante.nombre FROM fabricante LEFT JOIN producto ON fabricante.codigo = producto.codigo_fabricante WHERE producto.codigo IS NULL;
SELECT nombre FROM producto WHERE codigo_fabricante = (SELECT codigo FROM fabricante WHERE nombre = 'Lenovo');
SELECT * FROM producto WHERE precio = (SELECT MAX(precio) FROM producto WHERE codigo_fabricante = (SELECT codigo FROM fabricante WHERE nombre = 'Lenovo'));
SELECT producto.nombre, producto.precio FROM producto JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo WHERE fabricante.nombre = 'Lenovo' ORDER BY producto.precio DESC LIMIT 1;
SELECT nombre, precio FROM producto WHERE precio = (SELECT MIN(producto.precio) FROM producto JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo WHERE fabricante.nombre = 'Hewlett-Packard');
SELECT nombre, precio FROM producto WHERE precio >= (SELECT MAX(producto.precio) FROM producto JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo WHERE fabricante.nombre = 'Lenovo');
SELECT * FROM producto JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo WHERE fabricante.nombre = 'Asus' AND producto.precio > ( SELECT AVG(producto.precio) FROM producto JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo WHERE fabricante.nombre = 'Asus' );
USE universidad;
SELECT nombre, apellido1, apellido2 FROM ( SELECT DISTINCT persona.nif, persona.nombre, persona.apellido1, persona.apellido2 FROM persona JOIN alumno_se_matricula_asignatura ON persona.id = alumno_se_matricula_asignatura.id_alumno ) AS personas_unicas ORDER BY apellido1 ASC, apellido2 ASC, nombre ASC;
SELECT DISTINCT nombre, apellido1, apellido2, telefono FROM persona JOIN alumno_se_matricula_asignatura ON persona.id = alumno_se_matricula_asignatura.id_alumno WHERE telefono IS NULL;
SELECT DISTINCT nombre, apellido1, apellido2, fecha_nacimiento FROM persona JOIN alumno_se_matricula_asignatura ON persona.id = alumno_se_matricula_asignatura.id_alumno WHERE fecha_nacimiento BETWEEN '1999-01-01' AND '1999-12-31';
SELECT DISTINCT nombre, apellido1, apellido2, nif FROM persona JOIN profesor ON persona.id = profesor.id_profesor WHERE telefono IS NULL AND nif LIKE ('%K');
SELECT asignatura.nombre, asignatura.creditos, asignatura.tipo FROM asignatura JOIN grado ON asignatura.id_grado = grado.id WHERE grado.id = 7 AND asignatura.cuatrimestre = 1;
SELECT DISTINCT persona.nombre, persona.apellido1, persona.apellido2, departamento.nombre FROM persona JOIN profesor ON persona.id = profesor.id_profesor JOIN departamento ON departamento.id = profesor.id_departamento ORDER BY apellido1 DESC, apellido2 DESC, persona.nombre DESC;
SELECT asignatura.nombre, curso_escolar.anyo_inicio, curso_escolar.anyo_fin FROM asignatura JOIN alumno_se_matricula_asignatura ON asignatura.id = alumno_se_matricula_asignatura.id_asignatura JOIN curso_escolar ON alumno_se_matricula_asignatura.id_curso_escolar = curso_escolar.id WHERE alumno_se_matricula_asignatura.id_alumno = (SELECT id FROM persona WHERE nif = '26902806M');
SELECT departamento.nombre FROM grado JOIN asignatura ON grado.id = asignatura.id_grado JOIN profesor ON asignatura.id_profesor = profesor.id_profesor JOIN departamento ON profesor.id_departamento = departamento.id WHERE grado.nombre = 'Grado en Ingeniería Informática (Plan 2015)' GROUP BY departamento.nombre;
SELECT DISTINCT p.nombre, p.apellido1, p.apellido2 FROM persona p JOIN alumno_se_matricula_asignatura a_mat ON p.id = a_mat.id_alumno JOIN curso_escolar ce ON a_mat.id_curso_escolar = ce.id WHERE anyo_inicio = '2018';
SELECT dep.nombre, p.nombre, p.apellido1, p.apellido2 FROM persona p JOIN profesor pf ON p.id = pf.id_profesor LEFT JOIN departamento dep ON pf.id_departamento = dep.id ORDER BY dep.nombre DESC, p.apellido1 DESC, p.apellido2 DESC, p.nombre;
SELECT DISTINCT p.nombre, p.apellido1, p.apellido2 FROM persona p JOIN profesor pf ON p.id = pf.id_profesor LEFT JOIN departamento dep ON pf.id_departamento = dep.id WHERE pf.id_departamento IS NULL;
SELECT dep.nombre FROM departamento dep LEFT JOIN profesor ON dep.id = profesor.id_departamento WHERE profesor.id_departamento IS NULL;
SELECT DISTINCT CONCAT(p.nombre,' ',p.apellido1, ' ', p.apellido2) AS profesors_sense_asignatura FROM persona p JOIN profesor LEFT JOIN asignatura ON profesor.id_profesor = asignatura.id_profesor WHERE asignatura.nombre IS NULL GROUP BY profesors_sense_asignatura;
SELECT asignatura.nombre AS asignaturas_sin_profesor FROM asignatura LEFT JOIN profesor ON asignatura.id_profesor = profesor.id_profesor WHERE asignatura.id_profesor IS NULL;
SELECT dep.nombre FROM departamento dep LEFT JOIN profesor p ON dep.id = p.id_departamento LEFT JOIN asignatura a ON p.id_profesor = a.id_profesor LEFT JOIN alumno_se_matricula_asignatura ama ON a.id = ama.id_asignatura GROUP BY dep.id HAVING COUNT(ama.id_curso_escolar) = 0;
SELECT COUNT(DISTINCT p.id) FROM persona p JOIN alumno_se_matricula_asignatura ama ON p.id = ama.id_alumno;
SELECT COUNT(DISTINCT p.id) FROM persona p JOIN alumno_se_matricula_asignatura ama ON p.id = ama.id_alumno WHERE p.fecha_nacimiento BETWEEN '1999-01-01' AND '1999-12-31';
SELECT DISTINCT dep.nombre AS departamento, COUNT(profesor.id_profesor) AS numero_profesores FROM departamento dep JOIN profesor ON dep.id = profesor.id_departamento GROUP BY dep.nombre ORDER BY numero_profesores DESC;
SELECT DISTINCT dep.nombre, COUNT(profesor.id_profesor) FROM departamento dep LEFT JOIN profesor ON dep.id = profesor.id_departamento GROUP BY dep.nombre;
SELECT DISTINCT g.nombre, COUNT(a.id) AS asignaturas FROM grado g LEFT JOIN asignatura a ON g.id = a.id_grado GROUP BY g.nombre ORDER BY asignaturas DESC;